services:
  - type: web
    name: goku_agente
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python chatbot_v2.py
    envVars:
      - key: PORT
        value: 10000

        